version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "saas-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mdginv036be9"
s3_prefix = "saas-sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM CAPABILITY_AUTO_EXPAND"
disable_rollback = true
parameter_overrides = "AdminEmailParameter=\"fellipefreiire3@gmail.com\" SystemAdminRoleNameParameter=\"SystemAdmin\" AdminUserPoolCallbackURLParameter=\"http://example.com\" StageName=\"prod\""
image_repositories = []

[y]
[y.deploy]
[y.deploy.parameters]
stack_name = "saas-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1mdginv036be9"
s3_prefix = "saas-sam-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_AUTO_EXPAND CAPABILITY_NAMED_IAM"
disable_rollback = true
parameter_overrides = "AdminEmailParameter=\"fellipefreiire3@gmail.com\" SystemAdminRoleNameParameter=\"SystemAdmin\" AdminUserPoolCallbackURLParameter=\"http://example.com\" StageName=\"prod\""
image_repositories = []
